{% set name = "gracedb-sdk" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8fcc8f57fd88d4838633346f817f846c726ab297fd8650e3cb17d630de732a3

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - requests-gracedb

test:
  imports:
    - gracedb_sdk
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -m pip check
    - python -m pip show gracedb-sdk
    - python -m pytest --pyargs gracedb_sdk

about:
  home: https://git.ligo.org/emfollow/gracedb-sdk
  doc_url: https://gracedb-sdk.readthedocs.io/
  dev_url: https://git.ligo.org/emfollow/gracedb-sdk
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: REST API SDK for GraceDB
  description: A modern, performant REST API client for GraceDB, based on Requests

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
