{% set name = "gracedb-sdk" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 877680ad79b91b85eb291da7a5c31cd2eb1000c9659c9dfd87dbf8a01e092028

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - requests-gracedb

test:
  imports:
    - gracedb_sdk
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - python -m pip check
    - python -m pip show gracedb-sdk
    - python -m pytest tests

about:
  home: https://git.ligo.org/emfollow/gracedb-sdk
  doc_url: https://gracedb-sdk.readthedocs.io/
  dev_url: https://git.ligo.org/emfollow/gracedb-sdk
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: REST API SDK for GraceDB
  description: A modern, performant REST API client for GraceDB, based on Requests

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
