{% set name = "gracedb-sdk" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7c10b9cc28b6db5955cf4e2c726ac66b84d43a809eb05dd8d8130ce630173948

build:
  noarch: "python"
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - requests-gracedb

test:
  imports:
    - gracedb_sdk
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs gracedb_sdk

about:
  home: "https://git.ligo.org/emfollow/gracedb-sdk"
  doc_url: "https://gracedb-sdk.readthedocs.io/"
  dev_url: "https://git.ligo.org/emfollow/gracedb-sdk"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE.rst"
  summary: "REST API SDK for GraceDB"
  description: "A modern, performant REST API client for GraceDB, based on Requests"

extra:
  recipe-maintainers:
    - duncanmmacleod
